### ISSUE TITLE
[C#] Update onnxruntime_dependencies diagram with contributed operators API

### ISSUE THREAD

**Issue by GeorgeS2019** [microsoft/onnxruntime#11662]
Suggestion:

Make [contributed operators](https://github.com/microsoft/onnxruntime/blob/master/docs/ContribOperators.md) as **API accessible from e.g. C#**

https://github.com/microsoft/onnxruntime/blob/master/docs/onnxruntime_dependencies.png

![image](https://user-images.githubusercontent.com/49812372/170801253-0d04f525-2155-4ace-9415-95e941f63d97.png)

**Comment by GeorgeS2019** [comment]
An effective diagram could provide some idea of how to proceed with this [request: **How to implement a new operator** inference function?](https://github.com/microsoft/onnxruntime/issues/11678)

**Comment by GeorgeS2019** [comment]
related issues:
- [ ] [[C#] ContribOperators](https://github.com/microsoft/onnxruntime/issues/11564)
- [ ] [[Documentation, Windows, c#] Add an entry on Build for Custom Op development](https://github.com/microsoft/onnxruntime/issues/11657)
- [ ] [[C#] Documentation on how to coordinate the external Onnxruntime-Extension](https://github.com/microsoft/onnxruntime/issues/11655)
- [ ] [[C#] Basic build instruction to generate custom_op_library.dll](https://github.com/microsoft/onnxruntime/issues/11655)
- [ ] [[C#] Provide custom_op_library.dll](https://github.com/microsoft/onnxruntime/issues/11653)
