### ISSUE TITLE
NLP csharp example

### ISSUE THREAD

**Issue by connor-vr** [microsoft/onnxruntime#12100]
Could we get an example c# code of using an NLP model for inferencing? I personally would like one covering a conversational model but would appreciate any NLP model. I'm struggling to get it working in my app.

**Comment by natke** [comment]
Addressed by #12472

**Comment by natke** [comment]
@connor-vr Please have a look at https://onnxruntime.ai/docs/tutorials/csharp/bert-nlp-csharp-console-app.html and let us know if they helps to get you going!

**Comment by GeorgeS2019** [comment]
@natke 
[Create C# inference section and added C# BERT NLP](https://github.com/microsoft/onnxruntime/pull/12472) tutorial by @cassiebreviu is A BIG POSITIVE support to c# Onnx community

**Comment by GeorgeS2019** [comment]
@natke & @cassieapril 

[What's the advantage of using c interface](https://github.com/microsoft/onnxruntime/discussions/9311)?

> C is the lowest common denominator that allows us to write bindings for several other languages (C#, Java, Rust, etc) => To support **.Net P/Invoke**

I previously discuss on the [C API](https://github.com/microsoft/onnxruntime/issues/11655#issuecomment-1146016587)

![image](https://user-images.githubusercontent.com/49812372/171860534-428b4af0-d75f-41de-960a-ec9c9df517c5.png)

I would like to request **Effort & Support** on how to **expose** contributed Operators for C# Onnx users.

**Comment by GeorgeS2019** [comment]
- [ ] [[C#] ContribOperators: Possible to expose contributed operators as API accessible through c#?](https://github.com/microsoft/onnxruntime/issues/11564)

**Comment by GeorgeS2019** [comment]
related issues:
- [ ] [[C#] ContribOperators](https://github.com/microsoft/onnxruntime/issues/11564)
- [ ] [[Documentation, Windows, c#] Add an entry on Build for Custom Op development](https://github.com/microsoft/onnxruntime/issues/11657)
- [ ] [[C#] Documentation on how to coordinate the external Onnxruntime-Extension](https://github.com/microsoft/onnxruntime/issues/11655)
- [ ] [[C#] Basic build instruction to generate custom_op_library.dll](https://github.com/microsoft/onnxruntime/issues/11655)
- [ ] [[C#] Provide custom_op_library.dll](https://github.com/microsoft/onnxruntime/issues/11653)

**Comment by natke** [comment]
Original question was addressed by this tutorial: https://onnxruntime.ai/docs/tutorials/csharp/bert-nlp-csharp-console-app.html

**Comment by natke** [comment]
Fixed by #12472
